@testset "DrawBPD" begin

w = [2,1]; b = Rothe(w)

ltx = draw_bpd(b, mode=:ps)

@test ltx == "%% Auto-generated by draw_bpd\n\\psset{unit=0.7cm,linewidth=0.8pt}\n\\begin{pspicture}(0,0)(2,2)\n\\psline[linecolor=lightgray] (0,1)(2,1)\n\\psline[linecolor=lightgray] (1,0)(1,2)\n\\psline[linecolor=gray](0,0)(2,0)(2,2)(0,2)(0,0)\n\\psframe*[linecolor=orange!30] (0.00,1.00)(1.00,2.00)\n\\psline[linecolor=orange] (0.00,1.00)(1.00,1.00)(1.00,2.00)(0.00,2.00)(0.00,1.00)\n\\psbezier[linecolor=blue] (2.00,1.50) (1.50,1.50) (1.50,1.50) (1.50,1.00)\n\\psbezier[linecolor=blue] (1.00,0.50) (0.50,0.50) (0.50,0.50) (0.50,0.00)\n\\psline[linecolor=blue] (1.50,0.00)(1.50,1.00)\n\\psline[linecolor=blue] (1.00,0.50)(2.00,0.50)\n\\end{pspicture}\n"


end
